### ISSUE TITLE
transparency support

### ISSUE THREAD

**Issue by chausch** [ryanslikesocool/URP-Anaglyph3D#1]
dear ryan,
thanks for the great-working solution for anaglyph camera in urp!
i'm having trouble with transparency. i'm running unity 2021.0.3f1.
to be precise: i want to have particles in the anaglyph scene. this only works with opaque shaders. as soon as i switch alpha on, they are not rendered anymore!
could you have a look at this?
thanks so much!!!!
greetings from europe/vienna

**Comment by ryanslikesocool** [comment]
Thanks for bringing this to my attention.

This has been fixed with [release v2.0.0](https://github.com/ryanslikesocool/Anaglyph3D/releases/tag/v2.0.0), which also brings other improvements + fixes.
Be sure to read the updated readme to see how to set things up.

Let me know if there's any other issues 🙂

**Comment by chausch** [comment]
wow, fantastic!!! it seems everything works! 
thanks so much!!!! 😊
will keep you posted!
