### ISSUE TITLE
Errors using Unity 2021.3.25f1

### ISSUE THREAD

**Issue by hyperion2022** [ryanslikesocool/URP-Anaglyph3D#5]
I have two errors from the get-go:

error CS0117: 'RenderingUtils' does not contain a definition for 'ReAllocateIfNeeded'

error CS1061: 'ScriptableRenderer' does not contain a definition for 'cameraColorTargetHandle' and no accessible extension method 'cameraColorTargetHandle' accepting a first argument of type 'ScriptableRenderer' could be found (are you missing a using directive or an assembly reference?)

I am using the third person template and don't have enough low-level knowledge on the topic, could you please help me?

**Comment by ryanslikesocool** [comment]
Those errors are caused because your Unity + URP version doesn't have those APIs.
You're using Unity 2021.3.x, which I'm no longer supporting.  The last version of Anaglyph3D to support Unity 2021.3.x was [v2.1.1](https://github.com/ryanslikesocool/Anaglyph3D/releases/tag/v2.1.1).  If you installed via the package manager, you can link to a specific package version by opening up your project's `manifest.json` and adding `#v2.1.1` to the end of the git link.
```js
"com.developedwithlove.anaglyph" : "https://github.com/ryanslikesocool/Anaglyph3D.git#v2.1.1"
```

**Comment by hyperion2022** [comment]
It works! Thanks so much!
